import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { dirname, resolve } from "path";

export class SecretsManager {
  private secretsPath: string;
  private sharedMemoryPath: string;

  constructor(secretsPath: string, sharedMemoryPath: string) {
    this.secretsPath = secretsPath;
    this.sharedMemoryPath = sharedMemoryPath;
    mkdirSync(dirname(sharedMemoryPath), { recursive: true });
  }

  load(): Record<string, string> {
    if (!existsSync(this.secretsPath)) return {};
    try {
      return JSON.parse(readFileSync(this.secretsPath, "utf-8"));
    } catch {
      return {};
    }
  }

  save(secrets: Record<string, string>): void {
    writeFileSync(this.secretsPath, JSON.stringify(secrets, null, 2), "utf-8");
  }

  set(key: string, value: string): void {
    const secrets = this.load();
    secrets[key] = value;
    this.save(secrets);
    this.updateSharedMemory();
  }

  delete(key: string): boolean {
    const secrets = this.load();
    if (!(key in secrets)) return false;
    delete secrets[key];
    this.save(secrets);
    this.updateSharedMemory();
    return true;
  }

  list(): string[] {
    return Object.keys(this.load());
  }

  reload(): void {
    this.updateSharedMemory();
  }

  updateSharedMemory(): void {
    const secrets = this.load();

    let base = "";
    if (existsSync(this.sharedMemoryPath)) {
      const content = readFileSync(this.sharedMemoryPath, "utf-8");
      // Remove existing secrets section
      base = content.replace(/\n?## Secrets\n[\s\S]*?<!-- END SECRETS -->\n?/m, "");
    } else {
      base = "# Shared Memory\n\nGlobal facts shared across all agents.\n";
    }

    const secretKeys = Object.keys(secrets);
    if (secretKeys.length === 0) {
      writeFileSync(this.sharedMemoryPath, base.trimEnd() + "\n", "utf-8");
      return;
    }

    const lines = [
      "",
      "## Secrets",
      "<!-- AUTO-GENERATED BY SYSTEM. DO NOT EDIT MANUALLY -->",
      "The following credentials are available for use in commands and scripts.",
      "SECURITY: Never output these values in messages, logs, or memory files.",
      "",
    ];

    for (const [key, value] of Object.entries(secrets)) {
      lines.push(`- ${key}: ${value}`);
    }

    lines.push("<!-- END SECRETS -->");

    writeFileSync(this.sharedMemoryPath, base.trimEnd() + "\n" + lines.join("\n") + "\n", "utf-8");
    console.log(`[SecretsManager] Updated shared memory with ${secretKeys.length} secrets`);
  }

  ensureSharedMemoryBase(): void {
    if (!existsSync(this.sharedMemoryPath)) {
      const content = [
        "# Shared Memory",
        "",
        "Global facts shared across all agents.",
        "",
        "## Project Info",
        "- This is a multi-agent system running on TeleClaude",
        "- Agents coordinate in the General topic",
        "- Each agent has isolated memory in their own project directory",
        "",
      ].join("\n");
      writeFileSync(this.sharedMemoryPath, content, "utf-8");
    }
    this.updateSharedMemory();
  }
}
